version: '3.3'

volumes:
  pg_data:
  static:
  media:

services:
  backend:
    container_name: backend
    build: ./backend/
    command: |
      bash -c 'gunicorn --bind 0:10000 music_shop.wsgi'
    env_file:
      - .env
    volumes:
      - static:/app/static/
      - media:/app/media/

  nginx:
    container_name: nginx
    build: ./gateway/
    volumes:
      - static:/app/static/
      - media:/app/media/
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      backend:
        condition: service_started
