# Generated by Django 4.2.11 on 2024-03-25 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название')),
                ('short_description', models.CharField(blank=True, help_text='Введите краткое описание товара', max_length=255, null=True, verbose_name='Краткое описание')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, help_text='Загрузите изображение', null=True, upload_to='images/items/', verbose_name='Изображение')),
                ('price', models.IntegerField(help_text='Введите цену без акции', verbose_name='Цена без акции')),
                ('promo_price', models.IntegerField(blank=True, help_text='Введите цену по акции', null=True, verbose_name='Акционная цена')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('is_published', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, help_text='Отметить товар как опубликованный?', verbose_name='Опубликовано?')),
                ('is_on_main', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, help_text='Разместить на главной странице?', verbose_name='На главной странице?')),
                ('category', models.ForeignKey(help_text='Выберите категорию товара', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-add_date',),
            },
        ),
    ]
