# Generated by Django 4.2.11 on 2024-03-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название товара', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Введите описание товара', verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default=None, help_text='Загрузите изображение', null=True, upload_to='images/items/', verbose_name='Изображение')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('is_published', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, help_text='Отметить товар как опубликованный?', verbose_name='Опубликовано?')),
                ('is_on_main', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False, help_text='Разместить на главной странице?', verbose_name='На главной странице?')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('-add_date',),
            },
        ),
    ]
