# Generated by Django 4.2.11 on 2024-03-25 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Добавить запись в блоге', max_length=255, verbose_name='Запись в блоге')),
                ('slug', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='В слаге содержится недопустимый символ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
                ('text', models.TextField(help_text='Введите текст записи в блоге', verbose_name='Текст записи')),
                ('add_date', models.DateField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('is_published', models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=True, help_text='Отметить запись как опубликованную?', verbose_name='Опубликовано?')),
            ],
        ),
    ]
