# Generated by Django 4.2.11 on 2024-03-26 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Введите имя', max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию', max_length=255, verbose_name='Фамилия')),
                ('address', models.CharField(help_text='Введите ваш адрес в формате (город, улица, дом, корпус, квартира)', max_length=255, verbose_name='Укажите свой адрес')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, unique=True, verbose_name='email')),
                ('communication_method', models.CharField(help_text='Укажите предпочтительный способ связи (необязательно)', max_length=255, verbose_name='Способ связи')),
                ('order_notes', models.TextField(blank=True, help_text='Напишите ваши дополнительные пожелания (необязательно)', max_length=1000, null=True, verbose_name='Примечания к заказу')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Дата и время добавления')),
            ],
        ),
    ]
