# Generated by Django 4.2.11 on 2024-03-25 06:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='В слаге содержится недопустимый символ', regex='^[-a-zA-Z0-9_]+$')], verbose_name='Слаг')),
            ],
            options={
                'verbose_name': 'Создать тег',
                'verbose_name_plural': 'Создать теги',
            },
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(help_text='Выберите товар', on_delete=django.db.models.deletion.CASCADE, related_name='item_tags', to='item.item', verbose_name='Товар')),
                ('tag', models.ForeignKey(help_text='Выберите тег', on_delete=django.db.models.deletion.CASCADE, to='tags.tags', verbose_name='Тег')),
            ],
            options={
                'verbose_name': 'Присвоить тег',
                'verbose_name_plural': 'Присвоить теги',
            },
        ),
        migrations.AddConstraint(
            model_name='itemtag',
            constraint=models.UniqueConstraint(fields=('item', 'tag'), name='unique_item_tag'),
        ),
    ]
